apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: parser
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "20"
        spec:
          container:
            image: gcr.io/knative-broker/parser:0.0.6
          timeoutSeconds: 600

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: parser
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: records
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: parser
  reply:
    channel:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: parsed
